SDL_Window *window = NULL;
SDL_Renderer *renderer = NULL;
SDL_Surface *surface = NULL;
SDL_Event c;
SDL_Texture *back ;
SDL_Rect life[5];
SDL_Texture * heart;
SDL_Texture *Next_round;
SDL_Rect next_round;
 SDL_Event e;
bool quit = 1;
bool game = 1;
//SDL_Event mouse;
// TTF_Font *font = TTF_OpenFont("montserrat/Montserrat-Medium.otf",20);
// TTF_Font *font = TTF_OpenFont("montserrat/Montserrat-Black.otf",16);
